version: '3'
services:
  video-service:
    build:
      context: ./video-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./videos:/app/videos  # Mount the videos directory

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./user-service:/app

  content-service:
    build:
      context: ./content-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./content-service:/app